version: 0.0.{build}
configuration: Release
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true  
before_build:
- cmd: nuget restore
build:
  verbosity: detailed
  publish_nuget: true
  publish_nuget_symbols: true 
test: off
assembly_info:
  patch: true
  file: \Objectivity.Bot.HtmlBuilder\Properties\AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
environment:
  NugetApiKey:
    secure: Uv0dZyhFkHDm+qsH+qhtnM35q/U8pbVDBUWWlvP0VcCkOB26TOCDM+28wcVVKnao
artifacts:
  - path: '**\*.nupkg' 
deploy:
  - provider: NuGet
    api_key: $(NugetApiKey)
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true