version: 0.0.{build}
configuration: Release
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true  
before_build:
- cmd: nuget restore
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")

    {

    $sfbDir = (get-item $PSScriptRoot )

    $appConfigFile = [IO.Path]::Combine($sfbDir, 'Objectivity.Bot.HtmlBuilder\Objectivity.Bot.HtmlBuilder.nuspec')

    $appConfig = New-Object XML;

    $appConfig.Load($appConfigFile);

    $appConfig.package.metadata.version = "$env:APPVEYOR_REPO_TAG_NAME";

    $appConfig.Save($appConfigFile);

    }
build:
  verbosity: detailed
  publish_nuget: true
test: off
assembly_info:
  patch: true
  file: \Objectivity.Bot.HtmlBuilder\Properties\AssemblyInfo.cs
  assembly_version: '$(APPVEYOR_REPO_TAG_NAME)'
  assembly_file_version: '$(APPVEYOR_REPO_TAG_NAME)'
environment:
  NugetApiKey:
    secure: Uv0dZyhFkHDm+qsH+qhtnM35q/U8pbVDBUWWlvP0VcCkOB26TOCDM+28wcVVKnao
artifacts:
  - path: '**\*.nupkg'