version: 0.0.{build}
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
test: off
assembly_info:
  patch: true
  file: \Objectivity.Bot.HtmlBuilder\Properties\AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
environment:
  NugetApiKey:
    secure: Uv0dZyhFkHDm+qsH+qhtnM35q/U8pbVDBUWWlvP0VcCkOB26TOCDM+28wcVVKnao
deploy:
  - provider: NuGet
    api_key: $(NugetApiKey)
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true